// Generates the land outline of the deck's world map: one SVG path in a Natural Earth
// projection, plus the numbers needed to put a city on it at runtime.
//   node tools/deck/world.mjs > src/app/[artist]/experience/world.ts
import { readFileSync } from "node:fs";
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const W = 1000;
const topo = JSON.parse(readFileSync(new URL("../../node_modules/world-atlas/land-110m.json", import.meta.url), "utf8"));
const land = feature(topo, topo.objects.land);
const proj = geoNaturalEarth1().fitWidth(W, { type: "Sphere" });
const H = Math.ceil(geoPath(proj).bounds({ type: "Sphere" })[1][1]);
const [tx, ty] = proj.translate();
const k = proj.scale();
const path = geoPath(proj);
const round = (s) => s.replace(/(\d+\.\d{2})\d+/g, "$1");
process.stdout.write(`/* Generated by tools/deck/world.mjs from world-atlas (Natural Earth, 1:110m). Do not edit. */
export const WORLD_W = ${W};
export const WORLD_H = ${H};
/** Land, as one SVG path in the box above. */
export const LAND = "${round(path(land))}";
/** The projection's scale and translate, so a city can be placed at runtime. */
export const PROJ = { k: ${k}, tx: ${tx}, ty: ${ty} };
`);
