// Generates the deck's world map in a Natural Earth projection, 1000 units wide:
//   world.ts    the land, as one SVG path, plus the numbers to put a city on it at runtime
//   regions.ts  what the guest-spot map draws when it zooms in: country borders, the
//               US states (each its own path, so a pin knows its state) and the boxes
//               the map frames (contiguous US, every country)
// Sources: world-atlas (land and countries, 1:110m) and us-atlas (states, 1:10m,
// simplified down to the same weight). Run from the repo root:
//   node tools/deck/world.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature, mesh } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";

const W = 1000;
const read = (p) => JSON.parse(readFileSync(new URL(`../../node_modules/${p}`, import.meta.url), "utf8"));
const out = (f) => new URL(`../../src/app/[artist]/experience/${f}`, import.meta.url);

const topo = read("world-atlas/land-110m.json");
const land = feature(topo, topo.objects.land);
const proj = geoNaturalEarth1().fitWidth(W, { type: "Sphere" });
const H = Math.ceil(geoPath(proj).bounds({ type: "Sphere" })[1][1]);
const [tx, ty] = proj.translate();
const k = proj.scale();
const path = geoPath(proj);
const round = (s) => s.replace(/(\d+\.\d{2})\d+/g, "$1");
const box = (b) => `[${b[0][0].toFixed(1)}, ${b[0][1].toFixed(1)}, ${b[1][0].toFixed(1)}, ${b[1][1].toFixed(1)}]`;

writeFileSync(
  out("world.ts"),
  `/* Generated by tools/deck/world.mjs from world-atlas (Natural Earth, 1:110m). Do not edit. */
export const WORLD_W = ${W};
export const WORLD_H = ${H};
/** Land, as one SVG path in the box above. */
export const LAND = "${round(path(land))}";
/** The projection's scale and translate, so a city can be placed at runtime. */
export const PROJ = { k: ${k}, tx: ${tx}, ty: ${ty} };
`,
);

// Countries: the borders between them as one path, and each one's box, keyed by its
// lower-cased Natural Earth name. Boxes that wrap the antimeridian would span the whole
// map (Russia, Fiji); they are left out, and the map falls back to the stops themselves.
const countries = read("world-atlas/countries-110m.json");
const borders = round(path(mesh(countries, countries.objects.countries, (a, b) => a !== b)));
const countryBox = [];
for (const f of feature(countries, countries.objects.countries).features) {
  const b = path.bounds(f);
  if (b[1][0] - b[0][0] > W * 0.45) continue;
  countryBox.push(`  ${JSON.stringify(f.properties.name.toLowerCase())}: ${box(b)},`);
}

// US states: 1:10m is far more detail than the 110m land around it, so the topology is
// simplified until the fifty paths together weigh about as much as the world's land.
const ABBR = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
  "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
  "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND", "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI", "56": "WY",
};
let us = presimplify(read("us-atlas/states-10m.json"));
let states, weight = 0.0005;
for (;;) {
  const t = simplify(us, weight);
  states = feature(t, t.objects.states).features.filter((f) => ABBR[f.id] && f.id !== "02");
  const bytes = states.reduce((n, f) => n + round(path(f) ?? "").length, 0);
  if (bytes < 70_000 || weight > 1) {
    process.stderr.write(`states: weight ${weight}, ${bytes} bytes of path\n`);
    break;
  }
  weight *= 1.6;
}
const contiguous = states.filter((f) => f.id !== "15");
const stateRows = states.map((f) => `  { id: "${f.id}", abbr: "${ABBR[f.id]}", name: ${JSON.stringify(f.properties.name)}, box: ${box(path.bounds(f))}, d: "${round(path(f))}" },`);

writeFileSync(
  out("regions.ts"),
  `/* Generated by tools/deck/world.mjs from world-atlas (1:110m) and us-atlas (1:10m, simplified). Do not edit. */
/** Borders between countries, one path in the world box. */
export const BORDERS = "${borders}";
/** Each country's box [x0, y0, x1, y1], by its lower-cased Natural Earth name. */
export const COUNTRY_BOX: Record<string, [number, number, number, number]> = {
${countryBox.join("\n")}
};
/** The contiguous United States (with DC), the box the map frames for a US tour. */
export const US_BOX: [number, number, number, number] = ${box(path.bounds({ type: "FeatureCollection", features: contiguous }))};
export interface StateShape {
  id: string;
  abbr: string;
  name: string;
  box: [number, number, number, number];
  d: string;
}
/** The states (and DC, and Hawaii; Alaska would stretch the map), each its own path. */
export const STATES: StateShape[] = [
${stateRows.join("\n")}
];
`,
);
